### ISSUE TITLE
Error 403 with the basic function

### ISSUE THREAD

**Issue by PotatoesSQL** [DavideViolante/downdetector-api#4]
I think there is an error in the management of data recovery. Because when we execute the code: 
```js
async function down() {
    try {
        const response = await downdetector("google");
        console.log(response)
    } catch (err) {
        console.error(err);
    }
}
```
 present in the example. We have in the console the error : Request failed with status code 403

**Comment by DavideViolante** [comment]
I discovered that with Puppeteer it works again. I unarchived the repo and released a v2.0.0.
